# Generated by Django 2.2 on 2020-06-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200626_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
